### ISSUE TITLE
Loading indicator

### ISSUE THREAD

**Issue by jacmaes** [toddmotto/superbox#1]
Looks good, Todd, as always. One feature request: could you add a loading indicator to "soften" the transition when the large image loads, especially on slow connections?
Ah, while I'm at it, let's add another feature request: css animations instead of (or with a fallback to) jquery's animate, which is noticeably slower on some mobile devices as it doesn't use hardware acceleration.

**Comment by toddmotto** [comment]
Thanks! A loading indicator sounds nice, a nice white AJAX loader.

The jQuery animations are only to scroll the window to the right position (top of the rows). Apart from that it uses display block to show it, which will run perfect on mobiles :)

**Comment by jacmaes** [comment]
Thanks!
