### ISSUE TITLE
Multiple full images…

### ISSUE THREAD

**Issue by ghost** [toddmotto/superbox#2]
The full images are loaded using 'data-img', is there a method for loading more than one image? Essentially allowing multiple images to stack vertically…

**Comment by toddmotto** [comment]
Sure, just create as many data-\* attributes as you need, and call them with JavaScript. It might be worth setting up a loop perhaps to iterate through your images, specified inside a string.

**Comment by ghost** [comment]
Something like this?

```
            <img src="img/superbox/superbox-thumb-1.jpg" 
                    data-img="img/superbox/superbox-full-1.jpg"
                    data-img="img/superbox/superbox-full-2.jpg"
                    data-img="img/superbox/superbox-full-3.jpg"
                alt="" class="superbox-img">
```

**Comment by toddmotto** [comment]
No that wouldn't work as you'd either need to setup _different_ attribute names, or setup an array of objects inside one attribute and load them all in onclick.
