### ISSUE TITLE
Suggestion: use jQuery builder

### ISSUE THREAD

**Issue by englishextra** [toddmotto/superbox#7]
You can use http://projects.jga.me/jquery-builder/ to build custom jQuery for superbox to work - 

you need css dimensions effects offset

This is just a suggestion

**Comment by toddmotto** [comment]
Thanks, will check this out.

**Comment by englishextra** [comment]
Propose a resolution then close the issue. Right? Too much jQuery code for superbox to work, or is it not?

**Comment by toddmotto** [comment]
jQuery isn't packaged as part of the distribution, it's a CDN link, the user can choose how they want to include/bundle jQuery in.

**Comment by englishextra** [comment]
Yeah - yeah / just pointed out that if you want just a superbox the whole jQuery is too much/ So use some builders to minify.
